[package]
name = "A-test"
version = "0.1.0"
edition = "2021"

[dependencies]
vosk = "0.3.1"
cpal = "0.15"
hound = "3.5.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
device_query = "3.0.0"
byteorder = "1.4"